server:
  port: 9092
spring:
  application:
    name: DiscoveryService
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF